---
AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

# TODO: Reduce this value to default.
Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Enabled: false

Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
